import type { AddonDimensions, AddonObjectType } from '../../types/spacecraftAddons';
import { getObjectCatalogItem } from '../../data/objectCatalog';

interface Props { type: AddonObjectType; dimensions: AddonDimensions; color: string; isSelected?: boolean; isOutOfBounds?: boolean; }
interface ModelProps { color: string; isOutOfBounds: boolean; }

function Mat({ color, isOutOfBounds, roughness = 0.72, metalness = 0.06, transparent = false, opacity = 1 }: { color: string; isOutOfBounds: boolean; roughness?: number; metalness?: number; transparent?: boolean; opacity?: number }) {
  return <meshStandardMaterial color={isOutOfBounds ? '#E15151' : color} roughness={roughness} metalness={metalness} transparent={transparent || isOutOfBounds} opacity={isOutOfBounds ? 0.7 : opacity} />;
}
function darken(hex: string, factor: number) { if (!hex.startsWith('#')) return hex; const c=(v:number)=>Math.max(0,Math.min(255,v)); const r=c(Math.round(parseInt(hex.slice(1,3),16)*factor)); const g=c(Math.round(parseInt(hex.slice(3,5),16)*factor)); const b=c(Math.round(parseInt(hex.slice(5,7),16)*factor)); return `#${r.toString(16).padStart(2,'0')}${g.toString(16).padStart(2,'0')}${b.toString(16).padStart(2,'0')}`; }

function LampBase({ color, isOutOfBounds, tall }: ModelProps & { tall?: boolean }) { return <group><mesh position={[0,0.035,0]} castShadow><cylinderGeometry args={[0.16,0.18,0.07,32]} /><Mat color={darken(color,0.75)} isOutOfBounds={isOutOfBounds} metalness={0.2}/></mesh><mesh position={[0,tall?0.82:0.23,0]} castShadow><cylinderGeometry args={[0.025,0.025,tall?1.55:0.34,16]} /><Mat color={darken(color,0.7)} isOutOfBounds={isOutOfBounds} metalness={0.35}/></mesh><mesh position={[0,tall?1.52:0.44,0]} castShadow><coneGeometry args={[tall?0.23:0.16,tall?0.36:0.22,32]} /><Mat color="#F8E4B8" isOutOfBounds={isOutOfBounds} transparent opacity={0.84}/></mesh>{!isOutOfBounds && <pointLight position={[0,tall?1.48:0.48,0]} intensity={tall?0.38:0.24} color="#FFE1A6" distance={tall?3.4:2.2}/>}</group>; }
function Mirror({ color, isOutOfBounds }: ModelProps) { return <group><mesh position={[0,0.88,0]} castShadow><boxGeometry args={[0.75,1.75,0.06]}/><Mat color="#D7C4A7" isOutOfBounds={isOutOfBounds}/></mesh><mesh position={[0,0.88,0.035]}><boxGeometry args={[0.63,1.6,0.012]}/><Mat color={color} isOutOfBounds={isOutOfBounds} roughness={0.04} metalness={0.75} transparent opacity={0.72}/></mesh></group>; }
function Chair({ color, isOutOfBounds, office=false }: ModelProps & {office?: boolean}) { return <group><mesh position={[0,office?0.52:0.45,0]} castShadow><boxGeometry args={[office?0.58:0.52,office?0.12:0.08,office?0.55:0.5]}/><Mat color={color} isOutOfBounds={isOutOfBounds}/></mesh><mesh position={[0,office?0.9:0.78,-0.22]} castShadow><boxGeometry args={[office?0.55:0.52,office?0.72:0.62,0.09]}/><Mat color={darken(color,0.82)} isOutOfBounds={isOutOfBounds}/></mesh><mesh position={[0,0.27,0]}><cylinderGeometry args={[0.035,0.035,office?0.5:0.44,16]}/><Mat color="#3E3E3E" isOutOfBounds={isOutOfBounds}/></mesh></group>; }
function Laptop({ color, isOutOfBounds }: ModelProps) { return <group><mesh position={[0,0.018,0]} castShadow><boxGeometry args={[0.36,0.018,0.25]}/><Mat color={color} isOutOfBounds={isOutOfBounds} metalness={0.35}/></mesh><mesh position={[0,0.13,-0.12]} rotation={[-0.42,0,0]}><boxGeometry args={[0.36,0.21,0.014]}/><Mat color="#24272C" isOutOfBounds={isOutOfBounds}/></mesh><mesh position={[0,0.132,-0.129]} rotation={[-0.42,0,0]}><boxGeometry args={[0.31,0.16,0.006]}/><Mat color="#6EA7C7" isOutOfBounds={isOutOfBounds} transparent opacity={0.82}/></mesh></group>; }
function Monitor({ color, isOutOfBounds }: ModelProps) { return <group><mesh position={[0,0.32,0]} castShadow><boxGeometry args={[0.58,0.34,0.035]}/><Mat color={color} isOutOfBounds={isOutOfBounds}/></mesh><mesh position={[0,0.32,0.021]}><boxGeometry args={[0.5,0.27,0.01]}/><Mat color="#6EA7C7" isOutOfBounds={isOutOfBounds} transparent opacity={0.85}/></mesh><mesh position={[0,0.12,-0.02]}><boxGeometry args={[0.045,0.2,0.045]}/><Mat color={darken(color,0.75)} isOutOfBounds={isOutOfBounds}/></mesh></group>; }
function Plant({ color, isOutOfBounds }: ModelProps) { return <group><mesh position={[0,0.18,0]} castShadow><cylinderGeometry args={[0.18,0.23,0.36,28]}/><Mat color="#A46F4A" isOutOfBounds={isOutOfBounds}/></mesh>{[0,0.9,1.8,2.7,3.6].map((r,i)=><mesh key={i} position={[Math.cos(r)*0.11,0.54+i*0.06,Math.sin(r)*0.11]} rotation={[0.4,r,-0.2]}><sphereGeometry args={[0.18,18,12]}/><Mat color={color} isOutOfBounds={isOutOfBounds}/></mesh>)}</group>; }
function FlatBox({ color, isOutOfBounds, type }: ModelProps & {type: AddonObjectType}) { const args: [number,number,number] = type==='rug'?[1.8,0.025,1.2]:type==='tv'?[1.2,0.72,0.045]:type==='keyboard'?[0.42,0.035,0.14]:[0.34,0.18,0.22]; return <mesh position={[0,args[1]/2,0]} castShadow receiveShadow><boxGeometry args={args}/><Mat color={color} isOutOfBounds={isOutOfBounds}/></mesh>; }
function Speakers({ color, isOutOfBounds }: ModelProps) { return <group>{[-0.16,0.16].map(x=><mesh key={x} position={[x,0.16,0]} castShadow><boxGeometry args={[0.14,0.32,0.16]}/><Mat color={color} isOutOfBounds={isOutOfBounds}/></mesh>)}</group>; }

export function AddonObjectModel({ type, dimensions, color, isSelected = false, isOutOfBounds = false }: Props) {
  const base = getObjectCatalogItem(type)?.dimensions ?? { width: 1, depth: 1, height: 1 };
  const scale: [number, number, number] = [dimensions.width / base.width, dimensions.height / base.height, dimensions.depth / base.depth];
  return <group scale={scale}>{isSelected && <mesh position={[0,0.01,0]} rotation={[-Math.PI/2,0,0]}><ringGeometry args={[0.38,0.42,48]}/><meshBasicMaterial color="#8B6F47" transparent opacity={0.55}/></mesh>}{type==='tableLamp'&&<LampBase color={color} isOutOfBounds={isOutOfBounds}/>} {type==='floorLamp'&&<LampBase color={color} isOutOfBounds={isOutOfBounds} tall/>} {type==='floorMirror'&&<Mirror color={color} isOutOfBounds={isOutOfBounds}/>} {type==='chair'&&<Chair color={color} isOutOfBounds={isOutOfBounds}/>} {type==='officeChair'&&<Chair color={color} isOutOfBounds={isOutOfBounds} office/>} {type==='laptop'&&<Laptop color={color} isOutOfBounds={isOutOfBounds}/>} {type==='monitor'&&<Monitor color={color} isOutOfBounds={isOutOfBounds}/>} {type==='plant'&&<Plant color={color} isOutOfBounds={isOutOfBounds}/>} {['rug','books','tv','keyboard'].includes(type)&&<FlatBox color={color} isOutOfBounds={isOutOfBounds} type={type}/>} {type==='speakers'&&<Speakers color={color} isOutOfBounds={isOutOfBounds}/>}</group>;
}
