import { Armchair, BookOpen, Keyboard, Lamp, Laptop, Leaf, Monitor, RectangleHorizontal, Speaker, Tv } from 'lucide-react';
import { OBJECT_CATALOG } from '../../data/objectCatalog';
import type { AddonObjectType } from '../../types/spacecraftAddons';

interface Props { language?: 'ru' | 'en'; onAddObject: (type: AddonObjectType) => void; }
const ICONS: Record<AddonObjectType, React.ReactNode> = { tableLamp:<Lamp size={16}/>, floorLamp:<Lamp size={16}/>, floorMirror:<RectangleHorizontal size={16}/>, chair:<Armchair size={16}/>, officeChair:<Armchair size={16}/>, laptop:<Laptop size={16}/>, monitor:<Monitor size={16}/>, plant:<Leaf size={16}/>, rug:<RectangleHorizontal size={16}/>, books:<BookOpen size={16}/>, tv:<Tv size={16}/>, keyboard:<Keyboard size={16}/>, speakers:<Speaker size={16}/> };

export function ObjectCatalogPanel({ language = 'ru', onAddObject }: Props) {
  return <section className="rounded-xl overflow-hidden" style={{background:'rgba(255,255,255,0.86)',border:'1px solid rgba(139,111,71,0.12)',boxShadow:'0 1px 3px rgba(139,111,71,0.06)'}}><div className="px-4 py-3 border-b" style={{borderColor:'rgba(139,111,71,0.10)'}}><div className="text-xs" style={{fontWeight:700,color:'#5C4F3E',letterSpacing:'0.04em',textTransform:'uppercase'}}>{language==='ru'?'Каталог предметов':'Object catalog'}</div><div className="text-[11px] mt-0.5" style={{color:'#9B8E7E'}}>{language==='ru'?'Свет, техника, декор и мелкие предметы':'Lighting, devices, decor and small objects'}</div></div><div className="p-3 grid grid-cols-1 gap-1.5">{OBJECT_CATALOG.map(item=><button key={item.type} onClick={()=>onAddObject(item.type)} className="w-full flex items-center gap-3 p-2.5 rounded-xl text-left transition-all hover:translate-x-0.5" style={{background:'rgba(250,249,247,0.74)',border:'1px solid rgba(139,111,71,0.10)'}}><span className="w-10 h-10 rounded-xl flex items-center justify-center shrink-0" style={{background:`linear-gradient(135deg, ${item.color} 0%, ${item.color}CC 100%)`,color:'white',boxShadow:`0 4px 14px ${item.color}35`}}>{ICONS[item.type]}</span><span className="flex-1 min-w-0"><span className="block text-xs truncate" style={{color:'#1A1714',fontWeight:700}}>{language==='ru'?item.nameRu:item.nameEn}</span><span className="block text-[11px] truncate" style={{color:'#9B8E7E'}}>{language==='ru'?item.descriptionRu:item.descriptionEn}</span></span><span className="px-2 py-1 rounded-md text-[10px]" style={{background:'#8B6F47',color:'white',fontWeight:700}}>{language==='ru'?'Добавить':'Add'}</span></button>)}</div></section>;
}
