import { DoorOpen, Plus, Trash2, RectangleVertical } from 'lucide-react';
import type { ArchitecturalOpening, OpeningType, RoomSizeForOpenings, WallSide } from '../../types/spacecraftAddons';
import { clampOpeningToWall, createOpening, getWallLabel } from '../../lib/openingUtils';

interface Props { room: RoomSizeForOpenings; openings: ArchitecturalOpening[]; language?: 'ru' | 'en'; onChange: (openings: ArchitecturalOpening[]) => void; selectedOpeningId?: string | null; onSelect?: (id: string | null) => void; }

export function OpeningsPanel({ room, openings, language='ru', onChange, selectedOpeningId, onSelect }: Props) {
  const addOpening = (type: OpeningType) => { const item = createOpening(type, room); onChange([...openings, item]); onSelect?.(item.id); };
  const updateOpening = (id: string, updates: Partial<ArchitecturalOpening>) => onChange(openings.map(o => o.id === id ? clampOpeningToWall({ ...o, ...updates }, room) : o));
  const removeOpening = (id: string) => { onChange(openings.filter(o => o.id !== id)); if (selectedOpeningId === id) onSelect?.(null); };
  return <section className="rounded-xl overflow-hidden" style={{background:'rgba(255,255,255,0.86)',border:'1px solid rgba(139,111,71,0.12)',boxShadow:'0 1px 3px rgba(139,111,71,0.06)'}}><div className="px-4 py-3 border-b" style={{borderColor:'rgba(139,111,71,0.10)'}}><div className="text-xs" style={{fontWeight:700,color:'#5C4F3E',letterSpacing:'0.04em',textTransform:'uppercase'}}>{language==='ru'?'Окна и двери':'Windows and doors'}</div><div className="text-[11px] mt-0.5" style={{color:'#9B8E7E'}}>{language==='ru'?'Всегда крепятся к выбранной стене':'Always attached to a selected wall'}</div></div><div className="p-3 flex flex-col gap-2"><div className="grid grid-cols-2 gap-2"><button onClick={()=>addOpening('window')} className="flex items-center justify-center gap-2 rounded-xl px-3 py-2 text-xs" style={{background:'#F0E6D6',color:'#8B6F47',fontWeight:700,border:'1px solid rgba(139,111,71,0.16)'}}><Plus size={14}/>{language==='ru'?'Окно':'Window'}</button><button onClick={()=>addOpening('door')} className="flex items-center justify-center gap-2 rounded-xl px-3 py-2 text-xs" style={{background:'#8B6F47',color:'white',fontWeight:700,border:'1px solid rgba(139,111,71,0.16)'}}><Plus size={14}/>{language==='ru'?'Дверь':'Door'}</button></div>{openings.length===0&&<div className="rounded-xl px-3 py-3 text-xs" style={{background:'rgba(139,111,71,0.06)',border:'1px dashed rgba(139,111,71,0.2)',color:'#7A6E64'}}>{language==='ru'?'Окна и двери ещё не добавлены':'No windows or doors yet'}</div>}{openings.map((opening,index)=><OpeningCard key={opening.id} opening={opening} index={index} room={room} language={language} selected={selectedOpeningId===opening.id} onSelect={()=>onSelect?.(opening.id)} onUpdate={(u)=>updateOpening(opening.id,u)} onRemove={()=>removeOpening(opening.id)}/>)}</div></section>;
}

function OpeningCard({ opening, index, room, language, selected, onSelect, onUpdate, onRemove }: { opening: ArchitecturalOpening; index: number; room: RoomSizeForOpenings; language: 'ru' | 'en'; selected: boolean; onSelect: () => void; onUpdate: (updates: Partial<ArchitecturalOpening>) => void; onRemove: () => void; }) {
  const walls: WallSide[] = ['back','front','left','right'];
  return <div onClick={onSelect} className="rounded-xl p-3 flex flex-col gap-2 cursor-pointer" style={{background:selected?'rgba(139,111,71,0.10)':'rgba(250,249,247,0.82)',border:selected?'1px solid rgba(139,111,71,0.35)':'1px solid rgba(139,111,71,0.12)'}}><div className="flex items-center justify-between"><div className="flex items-center gap-2 text-xs" style={{color:'#5C4F3E',fontWeight:800}}>{opening.type==='door'?<DoorOpen size={14}/>:<RectangleVertical size={14}/>} {opening.type==='door' ? (language==='ru'?`Дверь ${index+1}`:`Door ${index+1}`) : (language==='ru'?`Окно ${index+1}`:`Window ${index+1}`)}</div><button onClick={(e)=>{e.stopPropagation();onRemove();}} className="w-7 h-7 rounded-lg flex items-center justify-center" style={{background:'rgba(196,75,75,0.08)',color:'#C44B4B'}}><Trash2 size={13}/></button></div><label className="flex items-center gap-2"><span className="text-xs flex-1" style={{color:'#7A6E64'}}>{language==='ru'?'Стена':'Wall'}</span><select value={opening.wall} onChange={(e)=>onUpdate({wall:e.target.value as WallSide})} className="text-xs rounded-lg px-2 py-1.5 outline-none" style={{width:108,background:'#FAF9F7',border:'1px solid rgba(139,111,71,0.18)',color:'#1A1714',fontWeight:600}}>{walls.map(w=><option key={w} value={w}>{getWallLabel(w,language)}</option>)}</select></label><NumberField label={language==='ru'?'Смещение':'Offset'} value={opening.offset} min={-10} max={10} step={0.1} onChange={(v)=>onUpdate({offset:v})}/><NumberField label={language==='ru'?'Ширина':'Width'} value={opening.width} min={0.35} max={opening.wall==='left'||opening.wall==='right'?room.depth:room.width} step={0.1} onChange={(v)=>onUpdate({width:v})}/><NumberField label={language==='ru'?'Высота':'Height'} value={opening.height} min={0.35} max={room.height} step={0.1} onChange={(v)=>onUpdate({height:v})}/>{opening.type==='window'&&<NumberField label={language==='ru'?'От пола':'From floor'} value={opening.heightFromFloor} min={0.15} max={room.height} step={0.1} onChange={(v)=>onUpdate({heightFromFloor:v})}/>}<div className="flex items-center gap-2 pt-1"><input type="color" value={opening.color} onChange={(e)=>onUpdate({color:e.target.value})} className="w-7 h-7 rounded-lg cursor-pointer" style={{border:'1px solid rgba(139,111,71,0.2)',padding:2}}/><span className="text-xs" style={{color:'#9B8E7E'}}>{opening.type==='door'?(language==='ru'?'дверь':'door'):(language==='ru'?'рама':'frame')}</span>{opening.type==='window'&&<><input type="color" value={opening.glassColor || '#AFC8D1'} onChange={(e)=>onUpdate({glassColor:e.target.value})} className="w-7 h-7 rounded-lg cursor-pointer ml-auto" style={{border:'1px solid rgba(139,111,71,0.2)',padding:2}}/><span className="text-xs" style={{color:'#9B8E7E'}}>{language==='ru'?'стекло':'glass'}</span></>}</div></div>;
}

function NumberField({ label, value, min, max, step, onChange }: { label: string; value: number; min: number; max: number; step: number; onChange: (value: number) => void; }) {
  const handle = (d:number)=>onChange(Math.max(min,Math.min(max,Math.round((value+d)*10)/10)));
  return <div className="flex items-center gap-2"><span className="text-xs flex-1" style={{color:'#7A6E64'}}>{label}</span><div className="flex items-center rounded-lg overflow-hidden" style={{border:'1px solid rgba(139,111,71,0.18)',background:'#FAF9F7'}}><button onClick={()=>handle(-step)} className="w-6 h-7" style={{color:'#8B6F47'}}>−</button><input type="number" value={value} min={min} max={max} step={step} onChange={(e)=>{const n=Number(e.target.value); if(!Number.isNaN(n)) onChange(Math.max(min,Math.min(max,n)));}} className="w-12 text-center text-xs bg-transparent outline-none" style={{color:'#1A1714',fontWeight:700}}/><button onClick={()=>handle(step)} className="w-6 h-7" style={{color:'#8B6F47'}}>+</button></div></div>;
}
