import type { Language } from '../types';

const ru = {
  app: {
    title: 'SPACECRAFT',
    subtitle: 'Планировщик интерьера',
    tagline: 'Увидь результат до покупки',
  },
  header: {
    save: 'Сохранить',
    import: 'Импорт',
    export: 'Экспорт',
    reset: 'Сбросить',
    saved: 'Сохранено',
    projectName: 'Мой проект',
  },
  room: {
    title: 'Параметры комнаты',
    width: 'Ширина',
    depth: 'Глубина',
    height: 'Высота',
    unit: 'м',
    dimensions: 'Размеры комнаты',
  },
  furniture: {
    catalog: 'Каталог мебели',
    add: 'Добавить',
    added: 'добавлен(а) в сцену',
    types: {
      wardrobe: 'Шкаф',
      sofa: 'Диван',
      bed: 'Кровать',
      table: 'Стол',
      dresser: 'Комод',
      nightstand: 'Тумба',
    },
    descriptions: {
      wardrobe: '1.8 × 0.6 × 2.1 м',
      sofa: '2.0 × 0.9 × 0.85 м',
      bed: '1.6 × 2.0 × 0.5 м',
      table: '1.2 × 0.7 × 0.75 м',
      dresser: '1.0 × 0.5 × 0.9 м',
      nightstand: '0.5 × 0.4 × 0.6 м',
    },
  },
  properties: {
    title: 'Свойства',
    name: 'Название',
    width: 'Ширина',
    depth: 'Глубина',
    height: 'Высота',
    positionX: 'Позиция X',
    positionZ: 'Позиция Z',
    rotation: 'Поворот',
    color: 'Цвет',
    delete: 'Удалить объект',
    noSelection: 'Объект не выбран',
    noSelectionHint: 'Нажмите на мебель в 3D-виде для редактирования параметров',
    dimensions: 'Размеры',
    position: 'Позиция',
    appearance: 'Внешний вид',
  },
  analytics: {
    title: 'Аналитика пространства',
    roomArea: 'Площадь комнаты',
    objects: 'Объектов',
    occupied: 'Занято',
    free: 'Свободно',
    fillRate: 'Заполнение',
    recommendation: 'Рекомендация',
    corridorWarnings: 'Узкие проходы',
    noWarnings: 'Проходы в норме',
    sqm: 'м²',
    pcs: 'шт.',
    recommendations: {
      empty: 'Начните добавлять мебель в пространство',
      tooEmpty: 'Комната выглядит свободно — можно добавить больше мебели',
      balanced: 'Планировка сбалансирована ✓',
      crowded: 'Проверьте проходы — комната заполнена',
      overloaded: 'Слишком много мебели для этой площади',
    },
  },
  camera: {
    view3d: '3D вид',
    viewTop: 'Вид сверху',
  },
  warnings: {
    outOfBounds: 'Объект выходит за границы комнаты',
    narrowCorridor: 'Проход менее 60 см между объектами',
    importError: 'Ошибка импорта: неверный формат файла',
  },
  actions: {
    confirmReset: 'Сбросить проект? Все данные будут удалены.',
    saveSuccess: 'Проект сохранён',
    exportSuccess: 'Проект экспортирован',
    importSuccess: 'Проект импортирован',
    resetSuccess: 'Проект сброшен',
  },
  colors: {
    title: 'Выбор цвета',
    presets: 'Готовые цвета',
  },
};

const en: typeof ru = {
  app: {
    title: 'SPACECRAFT',
    subtitle: 'Interior Planner',
    tagline: 'See the result before you buy',
  },
  header: {
    save: 'Save',
    import: 'Import',
    export: 'Export',
    reset: 'Reset',
    saved: 'Saved',
    projectName: 'My Project',
  },
  room: {
    title: 'Room Settings',
    width: 'Width',
    depth: 'Depth',
    height: 'Height',
    unit: 'm',
    dimensions: 'Room Dimensions',
  },
  furniture: {
    catalog: 'Furniture Catalog',
    add: 'Add',
    added: 'added to scene',
    types: {
      wardrobe: 'Wardrobe',
      sofa: 'Sofa',
      bed: 'Bed',
      table: 'Table',
      dresser: 'Dresser',
      nightstand: 'Nightstand',
    },
    descriptions: {
      wardrobe: '1.8 × 0.6 × 2.1 m',
      sofa: '2.0 × 0.9 × 0.85 m',
      bed: '1.6 × 2.0 × 0.5 m',
      table: '1.2 × 0.7 × 0.75 m',
      dresser: '1.0 × 0.5 × 0.9 m',
      nightstand: '0.5 × 0.4 × 0.6 m',
    },
  },
  properties: {
    title: 'Properties',
    name: 'Name',
    width: 'Width',
    depth: 'Depth',
    height: 'Height',
    positionX: 'Position X',
    positionZ: 'Position Z',
    rotation: 'Rotation',
    color: 'Color',
    delete: 'Delete Object',
    noSelection: 'No Object Selected',
    noSelectionHint: 'Click on furniture in the 3D view to edit its properties',
    dimensions: 'Dimensions',
    position: 'Position',
    appearance: 'Appearance',
  },
  analytics: {
    title: 'Space Analytics',
    roomArea: 'Room Area',
    objects: 'Objects',
    occupied: 'Occupied',
    free: 'Free',
    fillRate: 'Fill Rate',
    recommendation: 'Recommendation',
    corridorWarnings: 'Narrow passages',
    noWarnings: 'Passages are clear',
    sqm: 'm²',
    pcs: 'pcs.',
    recommendations: {
      empty: 'Start adding furniture to the space',
      tooEmpty: 'The room looks spacious — you can add more furniture',
      balanced: 'The layout is balanced ✓',
      crowded: 'Check passageways — room is getting full',
      overloaded: 'Too much furniture for this room size',
    },
  },
  camera: {
    view3d: '3D View',
    viewTop: 'Top View',
  },
  warnings: {
    outOfBounds: 'Object is outside room boundaries',
    narrowCorridor: 'Passage less than 60 cm between objects',
    importError: 'Import error: invalid file format',
  },
  actions: {
    confirmReset: 'Reset project? All data will be deleted.',
    saveSuccess: 'Project saved',
    exportSuccess: 'Project exported',
    importSuccess: 'Project imported',
    resetSuccess: 'Project reset',
  },
  colors: {
    title: 'Color Picker',
    presets: 'Preset Colors',
  },
};

export const translations = { ru, en } as const;

export function t(lang: Language): typeof ru {
  return translations[lang];
}
